// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budget.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBudgetPolicy = `-- name: GetBudgetPolicy :one
SELECT id, org_id, user_id, team_id,
       max_cost_usd_hour, max_cost_usd_day,
       max_tokens_hour, max_tokens_day,
       max_concurrent_streams
FROM budget_policies
WHERE org_id = $1
  AND (user_id = $2 OR user_id IS NULL)
  AND (team_id = $3 OR team_id IS NULL)
ORDER BY
    (user_id IS NOT NULL)::int DESC,
    (team_id IS NOT NULL)::int DESC
LIMIT 1
`

type GetBudgetPolicyParams struct {
	OrgID  pgtype.UUID `db:"org_id" json:"org_id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	TeamID pgtype.UUID `db:"team_id" json:"team_id"`
}

// Returns the most specific policy for the given user+team within an org.
// Specificity: user+team > user-only > team-only > org-wide.
func (q *Queries) GetBudgetPolicy(ctx context.Context, arg GetBudgetPolicyParams) (BudgetPolicy, error) {
	row := q.db.QueryRow(ctx, getBudgetPolicy, arg.OrgID, arg.UserID, arg.TeamID)
	var i BudgetPolicy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.TeamID,
		&i.MaxCostUsdHour,
		&i.MaxCostUsdDay,
		&i.MaxTokensHour,
		&i.MaxTokensDay,
		&i.MaxConcurrentStreams,
	)
	return i, err
}

const getCurrentWindowUsageDay = `-- name: GetCurrentWindowUsageDay :one
SELECT COALESCE(SUM(cost_usd), 0)::NUMERIC              AS cost_usd,
       COALESCE(SUM(input_tokens + output_tokens), 0)::BIGINT AS total_tokens,
       COALESCE(SUM(request_count), 0)::INT              AS request_count
FROM usage_agg_day
WHERE org_id = $1
  AND user_id = $2
  AND window_start = date_trunc('day', NOW() AT TIME ZONE 'UTC')
`

type GetCurrentWindowUsageDayParams struct {
	OrgID  pgtype.UUID `db:"org_id" json:"org_id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

type GetCurrentWindowUsageDayRow struct {
	CostUsd      pgtype.Numeric `db:"cost_usd" json:"cost_usd"`
	TotalTokens  int64          `db:"total_tokens" json:"total_tokens"`
	RequestCount int32          `db:"request_count" json:"request_count"`
}

// Returns aggregated usage for the current day window for a user.
func (q *Queries) GetCurrentWindowUsageDay(ctx context.Context, arg GetCurrentWindowUsageDayParams) (GetCurrentWindowUsageDayRow, error) {
	row := q.db.QueryRow(ctx, getCurrentWindowUsageDay, arg.OrgID, arg.UserID)
	var i GetCurrentWindowUsageDayRow
	err := row.Scan(&i.CostUsd, &i.TotalTokens, &i.RequestCount)
	return i, err
}

const getCurrentWindowUsageHour = `-- name: GetCurrentWindowUsageHour :one
SELECT COALESCE(SUM(cost_usd), 0)::NUMERIC              AS cost_usd,
       COALESCE(SUM(input_tokens + output_tokens), 0)::BIGINT AS total_tokens,
       COALESCE(SUM(request_count), 0)::INT              AS request_count
FROM usage_agg_hour
WHERE org_id = $1
  AND user_id = $2
  AND window_start = date_trunc('hour', NOW() AT TIME ZONE 'UTC')
`

type GetCurrentWindowUsageHourParams struct {
	OrgID  pgtype.UUID `db:"org_id" json:"org_id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

type GetCurrentWindowUsageHourRow struct {
	CostUsd      pgtype.Numeric `db:"cost_usd" json:"cost_usd"`
	TotalTokens  int64          `db:"total_tokens" json:"total_tokens"`
	RequestCount int32          `db:"request_count" json:"request_count"`
}

// Returns aggregated usage for the current hour window for a user.
func (q *Queries) GetCurrentWindowUsageHour(ctx context.Context, arg GetCurrentWindowUsageHourParams) (GetCurrentWindowUsageHourRow, error) {
	row := q.db.QueryRow(ctx, getCurrentWindowUsageHour, arg.OrgID, arg.UserID)
	var i GetCurrentWindowUsageHourRow
	err := row.Scan(&i.CostUsd, &i.TotalTokens, &i.RequestCount)
	return i, err
}

const getTeamWindowUsageDay = `-- name: GetTeamWindowUsageDay :one
SELECT COALESCE(SUM(cost_usd), 0)::NUMERIC              AS cost_usd,
       COALESCE(SUM(input_tokens + output_tokens), 0)::BIGINT AS total_tokens
FROM usage_agg_day
WHERE org_id = $1
  AND team_id = $2
  AND window_start = date_trunc('day', NOW() AT TIME ZONE 'UTC')
`

type GetTeamWindowUsageDayParams struct {
	OrgID  pgtype.UUID `db:"org_id" json:"org_id"`
	TeamID pgtype.UUID `db:"team_id" json:"team_id"`
}

type GetTeamWindowUsageDayRow struct {
	CostUsd     pgtype.Numeric `db:"cost_usd" json:"cost_usd"`
	TotalTokens int64          `db:"total_tokens" json:"total_tokens"`
}

func (q *Queries) GetTeamWindowUsageDay(ctx context.Context, arg GetTeamWindowUsageDayParams) (GetTeamWindowUsageDayRow, error) {
	row := q.db.QueryRow(ctx, getTeamWindowUsageDay, arg.OrgID, arg.TeamID)
	var i GetTeamWindowUsageDayRow
	err := row.Scan(&i.CostUsd, &i.TotalTokens)
	return i, err
}

const getTeamWindowUsageHour = `-- name: GetTeamWindowUsageHour :one
SELECT COALESCE(SUM(cost_usd), 0)::NUMERIC              AS cost_usd,
       COALESCE(SUM(input_tokens + output_tokens), 0)::BIGINT AS total_tokens
FROM usage_agg_hour
WHERE org_id = $1
  AND team_id = $2
  AND window_start = date_trunc('hour', NOW() AT TIME ZONE 'UTC')
`

type GetTeamWindowUsageHourParams struct {
	OrgID  pgtype.UUID `db:"org_id" json:"org_id"`
	TeamID pgtype.UUID `db:"team_id" json:"team_id"`
}

type GetTeamWindowUsageHourRow struct {
	CostUsd     pgtype.Numeric `db:"cost_usd" json:"cost_usd"`
	TotalTokens int64          `db:"total_tokens" json:"total_tokens"`
}

func (q *Queries) GetTeamWindowUsageHour(ctx context.Context, arg GetTeamWindowUsageHourParams) (GetTeamWindowUsageHourRow, error) {
	row := q.db.QueryRow(ctx, getTeamWindowUsageHour, arg.OrgID, arg.TeamID)
	var i GetTeamWindowUsageHourRow
	err := row.Scan(&i.CostUsd, &i.TotalTokens)
	return i, err
}

const upsertUsageAggDay = `-- name: UpsertUsageAggDay :exec
INSERT INTO usage_agg_day (org_id, user_id, team_id, provider, model, window_start, input_tokens, output_tokens, cost_usd, request_count)
VALUES ($1, $2, $3, $4, $5, date_trunc('day', NOW() AT TIME ZONE 'UTC'), $6, $7, $8, 1)
ON CONFLICT (org_id, user_id, team_id, provider, model, window_start)
DO UPDATE SET
    input_tokens  = usage_agg_day.input_tokens  + EXCLUDED.input_tokens,
    output_tokens = usage_agg_day.output_tokens + EXCLUDED.output_tokens,
    cost_usd      = usage_agg_day.cost_usd      + EXCLUDED.cost_usd,
    request_count = usage_agg_day.request_count + 1
`

type UpsertUsageAggDayParams struct {
	OrgID        pgtype.UUID    `db:"org_id" json:"org_id"`
	UserID       pgtype.UUID    `db:"user_id" json:"user_id"`
	TeamID       pgtype.UUID    `db:"team_id" json:"team_id"`
	Provider     string         `db:"provider" json:"provider"`
	Model        string         `db:"model" json:"model"`
	InputTokens  int64          `db:"input_tokens" json:"input_tokens"`
	OutputTokens int64          `db:"output_tokens" json:"output_tokens"`
	CostUsd      pgtype.Numeric `db:"cost_usd" json:"cost_usd"`
}

func (q *Queries) UpsertUsageAggDay(ctx context.Context, arg UpsertUsageAggDayParams) error {
	_, err := q.db.Exec(ctx, upsertUsageAggDay,
		arg.OrgID,
		arg.UserID,
		arg.TeamID,
		arg.Provider,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
	)
	return err
}

const upsertUsageAggHour = `-- name: UpsertUsageAggHour :exec
INSERT INTO usage_agg_hour (org_id, user_id, team_id, provider, model, window_start, input_tokens, output_tokens, cost_usd, request_count)
VALUES ($1, $2, $3, $4, $5, date_trunc('hour', NOW() AT TIME ZONE 'UTC'), $6, $7, $8, 1)
ON CONFLICT (org_id, user_id, team_id, provider, model, window_start)
DO UPDATE SET
    input_tokens  = usage_agg_hour.input_tokens  + EXCLUDED.input_tokens,
    output_tokens = usage_agg_hour.output_tokens + EXCLUDED.output_tokens,
    cost_usd      = usage_agg_hour.cost_usd      + EXCLUDED.cost_usd,
    request_count = usage_agg_hour.request_count + 1
`

type UpsertUsageAggHourParams struct {
	OrgID        pgtype.UUID    `db:"org_id" json:"org_id"`
	UserID       pgtype.UUID    `db:"user_id" json:"user_id"`
	TeamID       pgtype.UUID    `db:"team_id" json:"team_id"`
	Provider     string         `db:"provider" json:"provider"`
	Model        string         `db:"model" json:"model"`
	InputTokens  int64          `db:"input_tokens" json:"input_tokens"`
	OutputTokens int64          `db:"output_tokens" json:"output_tokens"`
	CostUsd      pgtype.Numeric `db:"cost_usd" json:"cost_usd"`
}

func (q *Queries) UpsertUsageAggHour(ctx context.Context, arg UpsertUsageAggHourParams) error {
	_, err := q.db.Exec(ctx, upsertUsageAggHour,
		arg.OrgID,
		arg.UserID,
		arg.TeamID,
		arg.Provider,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
	)
	return err
}
