// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BudgetPolicy struct {
	ID                   pgtype.UUID    `db:"id" json:"id"`
	OrgID                pgtype.UUID    `db:"org_id" json:"org_id"`
	UserID               pgtype.UUID    `db:"user_id" json:"user_id"`
	TeamID               pgtype.UUID    `db:"team_id" json:"team_id"`
	MaxCostUsdHour       pgtype.Numeric `db:"max_cost_usd_hour" json:"max_cost_usd_hour"`
	MaxCostUsdDay        pgtype.Numeric `db:"max_cost_usd_day" json:"max_cost_usd_day"`
	MaxTokensHour        *int64         `db:"max_tokens_hour" json:"max_tokens_hour"`
	MaxTokensDay         *int64         `db:"max_tokens_day" json:"max_tokens_day"`
	MaxConcurrentStreams *int32         `db:"max_concurrent_streams" json:"max_concurrent_streams"`
}

type Membership struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	OrgID  pgtype.UUID `db:"org_id" json:"org_id"`
	TeamID pgtype.UUID `db:"team_id" json:"team_id"`
	Role   string      `db:"role" json:"role"`
}

type Org struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RuntimeSetting struct {
	Key       string             `db:"key" json:"key"`
	Value     string             `db:"value" json:"value"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Team struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	OrgID     pgtype.UUID        `db:"org_id" json:"org_id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UsageAggDay struct {
	OrgID        pgtype.UUID        `db:"org_id" json:"org_id"`
	UserID       pgtype.UUID        `db:"user_id" json:"user_id"`
	TeamID       pgtype.UUID        `db:"team_id" json:"team_id"`
	Provider     string             `db:"provider" json:"provider"`
	Model        string             `db:"model" json:"model"`
	WindowStart  pgtype.Timestamptz `db:"window_start" json:"window_start"`
	InputTokens  int64              `db:"input_tokens" json:"input_tokens"`
	OutputTokens int64              `db:"output_tokens" json:"output_tokens"`
	CostUsd      pgtype.Numeric     `db:"cost_usd" json:"cost_usd"`
	RequestCount int32              `db:"request_count" json:"request_count"`
}

type UsageAggHour struct {
	OrgID        pgtype.UUID        `db:"org_id" json:"org_id"`
	UserID       pgtype.UUID        `db:"user_id" json:"user_id"`
	TeamID       pgtype.UUID        `db:"team_id" json:"team_id"`
	Provider     string             `db:"provider" json:"provider"`
	Model        string             `db:"model" json:"model"`
	WindowStart  pgtype.Timestamptz `db:"window_start" json:"window_start"`
	InputTokens  int64              `db:"input_tokens" json:"input_tokens"`
	OutputTokens int64              `db:"output_tokens" json:"output_tokens"`
	CostUsd      pgtype.Numeric     `db:"cost_usd" json:"cost_usd"`
	RequestCount int32              `db:"request_count" json:"request_count"`
}

type UsageEvent struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	OrgID          pgtype.UUID        `db:"org_id" json:"org_id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	TeamID         pgtype.UUID        `db:"team_id" json:"team_id"`
	VirtualKeyID   pgtype.UUID        `db:"virtual_key_id" json:"virtual_key_id"`
	Provider       string             `db:"provider" json:"provider"`
	Model          string             `db:"model" json:"model"`
	InputTokens    int32              `db:"input_tokens" json:"input_tokens"`
	OutputTokens   int32              `db:"output_tokens" json:"output_tokens"`
	CostUsd        pgtype.Numeric     `db:"cost_usd" json:"cost_usd"`
	ConversationID *string            `db:"conversation_id" json:"conversation_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Email     string             `db:"email" json:"email"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type VirtualKey struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	OrgID      pgtype.UUID        `db:"org_id" json:"org_id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	TeamID     pgtype.UUID        `db:"team_id" json:"team_id"`
	KeyHash    string             `db:"key_hash" json:"key_hash"`
	Prefix     string             `db:"prefix" json:"prefix"`
	Status     string             `db:"status" json:"status"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}
