// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateVirtualKey(ctx context.Context, arg CreateVirtualKeyParams) (VirtualKey, error)
	// Returns the most specific policy for the given user+team within an org.
	// Specificity: user+team > user-only > team-only > org-wide.
	GetBudgetPolicy(ctx context.Context, arg GetBudgetPolicyParams) (BudgetPolicy, error)
	// Returns aggregated usage for the current day window for a user.
	GetCurrentWindowUsageDay(ctx context.Context, arg GetCurrentWindowUsageDayParams) (GetCurrentWindowUsageDayRow, error)
	// Returns aggregated usage for the current hour window for a user.
	GetCurrentWindowUsageHour(ctx context.Context, arg GetCurrentWindowUsageHourParams) (GetCurrentWindowUsageHourRow, error)
	GetDailyUsageByOrg(ctx context.Context, arg GetDailyUsageByOrgParams) ([]GetDailyUsageByOrgRow, error)
	GetTeamWindowUsageDay(ctx context.Context, arg GetTeamWindowUsageDayParams) (GetTeamWindowUsageDayRow, error)
	GetTeamWindowUsageHour(ctx context.Context, arg GetTeamWindowUsageHourParams) (GetTeamWindowUsageHourRow, error)
	GetTopModelsByOrg(ctx context.Context, arg GetTopModelsByOrgParams) ([]GetTopModelsByOrgRow, error)
	GetTopUsersByOrg(ctx context.Context, arg GetTopUsersByOrgParams) ([]GetTopUsersByOrgRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserOrgs(ctx context.Context, userID pgtype.UUID) ([]GetUserOrgsRow, error)
	GetVirtualKey(ctx context.Context, arg GetVirtualKeyParams) (GetVirtualKeyRow, error)
	GetVirtualKeyByHash(ctx context.Context, keyHash string) (VirtualKey, error)
	InsertUsageEvent(ctx context.Context, arg InsertUsageEventParams) (InsertUsageEventRow, error)
	ListKeysByOrg(ctx context.Context, orgID pgtype.UUID) ([]ListKeysByOrgRow, error)
	ListVirtualKeysByUser(ctx context.Context, arg ListVirtualKeysByUserParams) ([]ListVirtualKeysByUserRow, error)
	RevokeVirtualKey(ctx context.Context, arg RevokeVirtualKeyParams) error
	UpdateVirtualKeyLastUsed(ctx context.Context, id pgtype.UUID) error
	UpsertUsageAggDay(ctx context.Context, arg UpsertUsageAggDayParams) error
	UpsertUsageAggHour(ctx context.Context, arg UpsertUsageAggHourParams) error
	UpsertUser(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
