// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyUsageByOrg = `-- name: GetDailyUsageByOrg :many
SELECT window_start::DATE            AS day,
       SUM(input_tokens)::BIGINT     AS input_tokens,
       SUM(output_tokens)::BIGINT    AS output_tokens,
       SUM(cost_usd)::NUMERIC(14, 8) AS cost_usd,
       SUM(request_count)::INT       AS request_count
FROM usage_agg_day
WHERE org_id = $1
  AND window_start >= $2
  AND window_start <  $3
GROUP BY window_start::DATE
ORDER BY day DESC
`

type GetDailyUsageByOrgParams struct {
	OrgID         pgtype.UUID        `db:"org_id" json:"org_id"`
	WindowStart   pgtype.Timestamptz `db:"window_start" json:"window_start"`
	WindowStart_2 pgtype.Timestamptz `db:"window_start_2" json:"window_start_2"`
}

type GetDailyUsageByOrgRow struct {
	Day          pgtype.Date    `db:"day" json:"day"`
	InputTokens  int64          `db:"input_tokens" json:"input_tokens"`
	OutputTokens int64          `db:"output_tokens" json:"output_tokens"`
	CostUsd      pgtype.Numeric `db:"cost_usd" json:"cost_usd"`
	RequestCount int32          `db:"request_count" json:"request_count"`
}

func (q *Queries) GetDailyUsageByOrg(ctx context.Context, arg GetDailyUsageByOrgParams) ([]GetDailyUsageByOrgRow, error) {
	rows, err := q.db.Query(ctx, getDailyUsageByOrg, arg.OrgID, arg.WindowStart, arg.WindowStart_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyUsageByOrgRow{}
	for rows.Next() {
		var i GetDailyUsageByOrgRow
		if err := rows.Scan(
			&i.Day,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.RequestCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopModelsByOrg = `-- name: GetTopModelsByOrg :many
SELECT model, provider,
       SUM(cost_usd)::NUMERIC(14, 8) AS total_cost_usd,
       SUM(request_count)::INT        AS total_requests
FROM usage_agg_day
WHERE org_id = $1
  AND window_start >= $2
  AND window_start <  $3
GROUP BY model, provider
ORDER BY total_cost_usd DESC
LIMIT $4
`

type GetTopModelsByOrgParams struct {
	OrgID         pgtype.UUID        `db:"org_id" json:"org_id"`
	WindowStart   pgtype.Timestamptz `db:"window_start" json:"window_start"`
	WindowStart_2 pgtype.Timestamptz `db:"window_start_2" json:"window_start_2"`
	Limit         int32              `db:"limit" json:"limit"`
}

type GetTopModelsByOrgRow struct {
	Model         string         `db:"model" json:"model"`
	Provider      string         `db:"provider" json:"provider"`
	TotalCostUsd  pgtype.Numeric `db:"total_cost_usd" json:"total_cost_usd"`
	TotalRequests int32          `db:"total_requests" json:"total_requests"`
}

func (q *Queries) GetTopModelsByOrg(ctx context.Context, arg GetTopModelsByOrgParams) ([]GetTopModelsByOrgRow, error) {
	rows, err := q.db.Query(ctx, getTopModelsByOrg,
		arg.OrgID,
		arg.WindowStart,
		arg.WindowStart_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopModelsByOrgRow{}
	for rows.Next() {
		var i GetTopModelsByOrgRow
		if err := rows.Scan(
			&i.Model,
			&i.Provider,
			&i.TotalCostUsd,
			&i.TotalRequests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopUsersByOrg = `-- name: GetTopUsersByOrg :many
SELECT u.id, u.email,
       SUM(a.cost_usd)::NUMERIC(14, 8) AS total_cost_usd,
       SUM(a.request_count)::INT        AS total_requests
FROM usage_agg_day a
JOIN users u ON u.id = a.user_id
WHERE a.org_id = $1
  AND a.window_start >= $2
  AND a.window_start <  $3
GROUP BY u.id, u.email
ORDER BY total_cost_usd DESC
LIMIT $4
`

type GetTopUsersByOrgParams struct {
	OrgID         pgtype.UUID        `db:"org_id" json:"org_id"`
	WindowStart   pgtype.Timestamptz `db:"window_start" json:"window_start"`
	WindowStart_2 pgtype.Timestamptz `db:"window_start_2" json:"window_start_2"`
	Limit         int32              `db:"limit" json:"limit"`
}

type GetTopUsersByOrgRow struct {
	ID            pgtype.UUID    `db:"id" json:"id"`
	Email         string         `db:"email" json:"email"`
	TotalCostUsd  pgtype.Numeric `db:"total_cost_usd" json:"total_cost_usd"`
	TotalRequests int32          `db:"total_requests" json:"total_requests"`
}

func (q *Queries) GetTopUsersByOrg(ctx context.Context, arg GetTopUsersByOrgParams) ([]GetTopUsersByOrgRow, error) {
	rows, err := q.db.Query(ctx, getTopUsersByOrg,
		arg.OrgID,
		arg.WindowStart,
		arg.WindowStart_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopUsersByOrgRow{}
	for rows.Next() {
		var i GetTopUsersByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.TotalCostUsd,
			&i.TotalRequests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUsageEvent = `-- name: InsertUsageEvent :one
INSERT INTO usage_events (org_id, user_id, team_id, virtual_key_id, provider, model, input_tokens, output_tokens, cost_usd, conversation_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, created_at
`

type InsertUsageEventParams struct {
	OrgID          pgtype.UUID    `db:"org_id" json:"org_id"`
	UserID         pgtype.UUID    `db:"user_id" json:"user_id"`
	TeamID         pgtype.UUID    `db:"team_id" json:"team_id"`
	VirtualKeyID   pgtype.UUID    `db:"virtual_key_id" json:"virtual_key_id"`
	Provider       string         `db:"provider" json:"provider"`
	Model          string         `db:"model" json:"model"`
	InputTokens    int32          `db:"input_tokens" json:"input_tokens"`
	OutputTokens   int32          `db:"output_tokens" json:"output_tokens"`
	CostUsd        pgtype.Numeric `db:"cost_usd" json:"cost_usd"`
	ConversationID *string        `db:"conversation_id" json:"conversation_id"`
}

type InsertUsageEventRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertUsageEvent(ctx context.Context, arg InsertUsageEventParams) (InsertUsageEventRow, error) {
	row := q.db.QueryRow(ctx, insertUsageEvent,
		arg.OrgID,
		arg.UserID,
		arg.TeamID,
		arg.VirtualKeyID,
		arg.Provider,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
		arg.ConversationID,
	)
	var i InsertUsageEventRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
