// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const getUserOrgs = `-- name: GetUserOrgs :many
SELECT o.id, o.name, m.role
FROM orgs o
JOIN memberships m ON m.org_id = o.id
WHERE m.user_id = $1
ORDER BY o.name
`

type GetUserOrgsRow struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
	Role string      `db:"role" json:"role"`
}

func (q *Queries) GetUserOrgs(ctx context.Context, userID pgtype.UUID) ([]GetUserOrgsRow, error) {
	rows, err := q.db.Query(ctx, getUserOrgs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserOrgsRow{}
	for rows.Next() {
		var i GetUserOrgsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (email) VALUES ($1)
ON CONFLICT (email) DO UPDATE SET email = EXCLUDED.email
RETURNING id, email, created_at
`

func (q *Queries) UpsertUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}
