// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: virtual_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVirtualKey = `-- name: CreateVirtualKey :one
INSERT INTO virtual_keys (org_id, user_id, team_id, key_hash, prefix)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, user_id, team_id, key_hash, prefix, status, created_at, last_used_at, revoked_at
`

type CreateVirtualKeyParams struct {
	OrgID   pgtype.UUID `db:"org_id" json:"org_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
	TeamID  pgtype.UUID `db:"team_id" json:"team_id"`
	KeyHash string      `db:"key_hash" json:"key_hash"`
	Prefix  string      `db:"prefix" json:"prefix"`
}

func (q *Queries) CreateVirtualKey(ctx context.Context, arg CreateVirtualKeyParams) (VirtualKey, error) {
	row := q.db.QueryRow(ctx, createVirtualKey,
		arg.OrgID,
		arg.UserID,
		arg.TeamID,
		arg.KeyHash,
		arg.Prefix,
	)
	var i VirtualKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.TeamID,
		&i.KeyHash,
		&i.Prefix,
		&i.Status,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getVirtualKey = `-- name: GetVirtualKey :one
SELECT id, org_id, user_id, team_id, prefix, status, created_at, last_used_at, revoked_at
FROM virtual_keys
WHERE id = $1 AND org_id = $2
`

type GetVirtualKeyParams struct {
	ID    pgtype.UUID `db:"id" json:"id"`
	OrgID pgtype.UUID `db:"org_id" json:"org_id"`
}

type GetVirtualKeyRow struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	OrgID      pgtype.UUID        `db:"org_id" json:"org_id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	TeamID     pgtype.UUID        `db:"team_id" json:"team_id"`
	Prefix     string             `db:"prefix" json:"prefix"`
	Status     string             `db:"status" json:"status"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) GetVirtualKey(ctx context.Context, arg GetVirtualKeyParams) (GetVirtualKeyRow, error) {
	row := q.db.QueryRow(ctx, getVirtualKey, arg.ID, arg.OrgID)
	var i GetVirtualKeyRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.TeamID,
		&i.Prefix,
		&i.Status,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getVirtualKeyByHash = `-- name: GetVirtualKeyByHash :one
SELECT id, org_id, user_id, team_id, key_hash, prefix, status, created_at, last_used_at, revoked_at
FROM virtual_keys
WHERE key_hash = $1
`

func (q *Queries) GetVirtualKeyByHash(ctx context.Context, keyHash string) (VirtualKey, error) {
	row := q.db.QueryRow(ctx, getVirtualKeyByHash, keyHash)
	var i VirtualKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.TeamID,
		&i.KeyHash,
		&i.Prefix,
		&i.Status,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listKeysByOrg = `-- name: ListKeysByOrg :many
SELECT id, user_id, team_id, prefix, status, created_at, last_used_at, revoked_at
FROM virtual_keys
WHERE org_id = $1
ORDER BY created_at DESC
`

type ListKeysByOrgRow struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	TeamID     pgtype.UUID        `db:"team_id" json:"team_id"`
	Prefix     string             `db:"prefix" json:"prefix"`
	Status     string             `db:"status" json:"status"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) ListKeysByOrg(ctx context.Context, orgID pgtype.UUID) ([]ListKeysByOrgRow, error) {
	rows, err := q.db.Query(ctx, listKeysByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKeysByOrgRow{}
	for rows.Next() {
		var i ListKeysByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TeamID,
			&i.Prefix,
			&i.Status,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVirtualKeysByUser = `-- name: ListVirtualKeysByUser :many
SELECT id, org_id, user_id, team_id, prefix, status, created_at, last_used_at, revoked_at
FROM virtual_keys
WHERE user_id = $1 AND org_id = $2
ORDER BY created_at DESC
`

type ListVirtualKeysByUserParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	OrgID  pgtype.UUID `db:"org_id" json:"org_id"`
}

type ListVirtualKeysByUserRow struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	OrgID      pgtype.UUID        `db:"org_id" json:"org_id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	TeamID     pgtype.UUID        `db:"team_id" json:"team_id"`
	Prefix     string             `db:"prefix" json:"prefix"`
	Status     string             `db:"status" json:"status"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) ListVirtualKeysByUser(ctx context.Context, arg ListVirtualKeysByUserParams) ([]ListVirtualKeysByUserRow, error) {
	rows, err := q.db.Query(ctx, listVirtualKeysByUser, arg.UserID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVirtualKeysByUserRow{}
	for rows.Next() {
		var i ListVirtualKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.TeamID,
			&i.Prefix,
			&i.Status,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeVirtualKey = `-- name: RevokeVirtualKey :exec
UPDATE virtual_keys
SET status = 'revoked', revoked_at = NOW()
WHERE id = $1 AND org_id = $2
`

type RevokeVirtualKeyParams struct {
	ID    pgtype.UUID `db:"id" json:"id"`
	OrgID pgtype.UUID `db:"org_id" json:"org_id"`
}

func (q *Queries) RevokeVirtualKey(ctx context.Context, arg RevokeVirtualKeyParams) error {
	_, err := q.db.Exec(ctx, revokeVirtualKey, arg.ID, arg.OrgID)
	return err
}

const updateVirtualKeyLastUsed = `-- name: UpdateVirtualKeyLastUsed :exec
UPDATE virtual_keys
SET last_used_at = NOW()
WHERE id = $1 AND org_id = $2
`

type UpdateVirtualKeyLastUsedParams struct {
	ID    pgtype.UUID `db:"id" json:"id"`
	OrgID pgtype.UUID `db:"org_id" json:"org_id"`
}

func (q *Queries) UpdateVirtualKeyLastUsed(ctx context.Context, arg UpdateVirtualKeyLastUsedParams) error {
	_, err := q.db.Exec(ctx, updateVirtualKeyLastUsed, arg.ID, arg.OrgID)
	return err
}
